### ISSUE TITLE
Scripts and facet values not loading in FacetWP 2.0.10

### ISSUE THREAD

**Issue by emilekott** [FacetWP/facetwp-select2#2]
Hi, Thanks for the pluign.

When I installed with latest version of FacetWP, it looked like select2 js was being called too later.

I altered the front_scripts() function to load the scripts in script tags rather than using wp_enqueue_script to make it more similar to those in FacetWP and force the loading order:
```php
 /**
     * Output any front-end scripts
     */
    function front_scripts() {
?>
<link rel='stylesheet' id='select2-css'  href='<?php echo plugins_url( 'facetwp-select2' ); ?>/select2/select2.css?ver=3.5.1' type='text/css' media='all' />
<script type="text/javascript" src='<?php echo plugins_url( 'facetwp-select2' ); ?>/select2/select2.min.js?ver=3.5.1'></script>
<script>
(function($) {
    wp.hooks.addAction('facetwp/refresh/select2', function($this, facet_name) {
        $this.find('.facetwp-select2').select2('destroy');
        FWP.facets[facet_name] = $this.find('.facetwp-select2').val() || [];
    });

    wp.hooks.addAction('facetwp/ready', function() {
        $(document).on('change', '.facetwp-facet .facetwp-select2', function() {
            FWP.autoload();
        });
    });

    $(document).on('facetwp-loaded', function() {
        $('.facetwp-type-select2').each(function() {
            var facet_name = $(this).attr('data-name');
            var placeholder = FWP.settings[facet_name] ? FWP.settings[facet_name]['placeholder'] : '';
            $(this).find('.facetwp-select2').select2({
                width: 'element',
                placeholder: placeholder
            });
        });
    });
})(jQuery);
</script>
<?php
    }
```

Also, the Facet values weren't loading so I also altered the render( $params ) function:
```php
 /**
     * Generate the facet HTML
     */
    function render( $params ) {

       $output = '';
        $facet = $params['facet'];
        $values = (array) $params['values'];
        $selected_values = (array) $params['selected_values'];

        if ( isset( $facet['hierarchical'] ) && 'yes' == $facet['hierarchical'] ) {
            $values = FWP()->helper->sort_taxonomy_values( $params['values'], $facet['orderby'] );
        }

        $label_any = empty( $facet['label_any'] ) ? __( 'Any', 'fwp' ) : sprintf( __( '%s', 'fwp' ), $facet['label_any'] );

        $output .= '<select class="facetwp-select2" multiple="multiple" style="width: 100%;">';
        //$output .= '<option value="">' . esc_attr( $label_any ) . '</option>';

        foreach ( $values as $result ) {
            $selected = in_array( $result['facet_value'], $selected_values ) ? ' selected' : '';

            $display_value = '';
            for ( $i = 0; $i < (int) $result['depth']; $i++ ) {
                $display_value .= '&nbsp;&nbsp;';
            }

            // Determine whether to show counts
            $display_value .= $result['facet_display_value'];
            $show_counts = apply_filters( 'facetwp_facet_dropdown_show_counts', true );
            if ( $show_counts ) {
                $display_value .= ' (' . $result['counter'] . ')';
            }

            $output .= '<option value="' . $result['facet_value'] . '"' . $selected . '>' . $display_value . '</option>';
        }

        $output .= '</select>';
        return $output;
    }
```

All seems to be working well with FacetWP 2.0.10

**Comment by Masterrenny** [comment]
Ive changed the code to what youve suggested however it still doesnt load for me, i keep getting 

Uncaught TypeError: $this.find(...).select2 is not a function

What version of jquery is needed for select2? or isnt that whats coursing this error

**Comment by emilekott** [comment]
I am guessing your problem is caused by the select2 function being called by your code BEFORE it's defined.

Did you change the code for front_scripts() - this is the bit that changes the order...
